config/routes.rb
Rails.application.routes.draw do
  resources :vaccination_centers
  resources :vaccines
  resources :turns
  resources :applied_vaccines, :path => 'applied_vaccine'
  root 'user_profiles#me'

  # Sessions routes
  get '/auth/login', to: 'sessions#login'
  post '/auth/login', to: 'sessions#create'
  get '/auth/logout', to: 'sessions#destroy'

  # Turns routes
  get '/show_all', to: 'turns#show_all', as: 'show_all'
  get '/pending_turns', to: 'turns#pending_turns'
  get '/new_manual', to: 'turns#new_manual', as: 'new_manual'
  post '/new_manual', to: 'turns#create_manual'


  # Campaigns routes
  get '/campaigns/:id/load_batch', to: 'campaigns#load_batch', as: 'load_batch'
  patch 'campaigns/:id', to: 'campaigns#update', as: 'campaign'
  get '/campaigns/:id/assign_turns', to: 'campaigns#assign_turns', as: 'assign_turns'
  post '/campaigns/:id/assign_turns', to: 'campaigns#assign_turns_to_campaign', as: 'assign_turns_to_campaign'
  # Vaccines routes
  get '/applied_vaccines/new', to: 'applied_vaccines#new', as: 'new_applied_vaccines'
  post '/applied_vaccines/new', to: 'turns#pending_turns'

  
  # Profiles routes
  
  get '/profile/me', to: 'user_profiles#me', as: 'me'
  get '/profile/me/edit', to: 'user_profiles#edit', as: 'edit_profile'
  patch '/profile/me/edit', to: 'user_profiles#update', as: 'update_profile'
  get '/auth/signin/profile', to: 'user_profiles#new', as: 'new_user_profile'
  post '/auth/signin/profile', to: 'user_profiles#create', as: 'create_user_profile'
  # Accounts routes
  get '/auth/signin/account', to: 'user_accounts#new', as: 'new_user_account'
  post '/auth/signin/account', to: 'user_accounts#create', as: 'create_user_account'
  get '/accounts/set_password', to: 'user_accounts#set_password', as: 'set_password'
  patch '/accounts/set_password', to: 'user_accounts#update_password', as: 'update_password'

  # VaccinationCenters routes
 
  patch '/vaccination_centers/edit', to: 'vaccination_centers#update', as: 'update_vaccination_center'

  resources :users, :except => [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_account.rb
class UserAccount
    include ActiveModel::Model
    include UsersHelper

    attr_accessor :email, :password
    validates :email, :presence => true
    validates :password, length: { minimum: 8 }
    validates_presence_of :password, :on => [:create, :update]
    validate :email_uniqueness?
end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
    include SessionsHelper, RolesHelper
    skip_before_action :require_login, only: [:new, :create]
    layout 'auth'

    def new
        @user_account = UserAccount.new
        
        if logged_in?
            if is_organization_member?
                render layout: 'application'
            else
                redirect_to root_path
            end
        end
    end

    def create
        @user_account = UserAccount.new(user_account_params)
  
        if @user_account.valid?
            # The values from the previous form step need to be
            # retrieved from the session store.
            full_params = user_account_params.merge(
                first_name: session['user_profile']['first_name'],
                last_name: session['user_profile']['last_name'],
                document_number: session['user_profile']['document_number'],
                birthdate: session['user_profile']['birthdate'],
                comorbidity: session['user_profile']['comorbidity']
            )
    
            # Here we finally carry out the ultimate objective:
            # creating a User record in the database.
            @user = User.create!(full_params)
            # Upon successful completion of the form we need to
            # clean up the session.
            session.delete('user_profile')

            if !logged_in?
                session[:user_id] = @user.id
                session[:expires_at] = Time.now + 3.hours
                flash[:success] = I18n.t('auth.sign_in.success')
                redirect_to root_path
            else
                flash[:success] = I18n.t('add_user.second_step.success')
                redirect_to turns_url
            end
    
        else
            if logged_in?
                if is_organization_member?
                    render layout: 'application', template: 'user_accounts/new'
                else
                    redirect_to root_path
                end
            else
                render :new
            end
        end
    end

    def set_password
        @user = User.find_signed!(params[:token], purpose: :set_password)
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to root_path, alert: I18n.t('auth.set_password.invalid_token')
    end

    def update_password
        @user = User.find_signed!(params[:token], purpose: :set_password)
        if @user.update(password: params[:user][:password])
            session[:user_id] = @user.id
            session[:expires_at] = Time.now + 3.hours
            flash[:success] = I18n.t('auth.set_password.success')
            redirect_to root_path
        else
            flash[:error] = I18n.t('base_text.error')
            render :set_password
        end 
    end


    private

    def user_account_params
        params.require(:user_account).permit(
            :email,
            :password
        )
    end
end

app/views/user_accounts/new.html.erb
<% adjective = logged_in? ? t('adjective.third') :  t('adjective.second') %>

<%= stylesheet_link_tag 'sessions', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= form_for @user_account, url: create_user_account_path, html: {class: "auth-form row needs-validation", validate: "validate"} do |f| %>
    <h1>
        <%= logged_in? ? t('add_user.second_step.title') : t('auth.sign_in.second_step.title') %>
    </h1>
    <% invalid = @user_account.errors.include?(:email) %>
    <div class="form-group col-12 mb-3">
        <%= f.label :email, t(:email), class: "form-label" %>
        <%= f.email_field :email, placeholder: t(:email_placeholder, adjective: adjective), class: "form-control #{'is-invalid' if invalid}", :required => true %>
        <% if invalid %>
            <div class="invalid-feedback">
                <%= show_errors @user_account, :email %>
            </div>  
        <% end %>
    </div>
    <% invalid = @user_account.errors.include?(:password) %>
    <div class="form-group col-12 mb-3">
        <%= f.label :password, t(:password), class: "form-label" %>
        <%= f.password_field :password, placeholder: t(:password_placeholder), class: "form-control #{'is-invalid' if invalid}", :required => true %>
        <% if invalid %>
            <div class="invalid-feedback">
                <%= show_errors @user_account, :password %>
            </div>  
        <% end %>
    </div>
    <% if logged_in? %>
        <%= f.submit t('add_user.second_step.button'), class: "btn btn-primary", formnovalidate: true %>
    <% else %>
        <%= f.submit t('auth.sign_in.second_step.button'), class: "btn btn-primary", formnovalidate: true %>
    <% end %>
    <% if !logged_in? %>
        <div class="mb-3 mt-3 text-center invite-container">
            <p class="invite">
                <%= t 'auth.sign_in.account' %>
                <%= link_to t('auth.sign_in.login_invite'), auth_login_path%>
            </p>
        </div>
    <% end %>
<% end %>

app/views/user_accounts/set_password.html.erb
<%= form_with model: @user, url: update_password_path(token: params[:token]), html: {class: "auth-form row needs-validation", validate: "validate"} do |form| %>
    <h1>
        <%= t 'auth.set_password.title' %>
    </h1>
    <% invalid = @user.errors.include?(:password) %>
    <div class="form-group col-12 mb-3">
        <%= form.label :password, t(:password), class: "form-label" %>
        <%= form.password_field :password, placeholder: t(:password_placeholder), class: "form-control #{'is-invalid' if invalid}", :required => true, minlength: 8 %>
        <% if invalid %>
            <div class="invalid-feedback">
                <%= show_errors @user, :password %>
            </div>  
        <% end %>
    </div>
    <%= form.submit t('base_text.save'), class: "btn btn-primary" %>
<% end %>