config/routes.rb
Rails.application.routes.draw do
  resources :vaccination_centers
  resources :vaccines
  resources :turns
  resources :applied_vaccines, :path => 'applied_vaccine'
  root 'user_profiles#me'

  # Sessions routes
  get '/auth/login', to: 'sessions#login'
  post '/auth/login', to: 'sessions#create'
  get '/auth/logout', to: 'sessions#destroy'

  # Turns routes
  get '/show_all', to: 'turns#show_all', as: 'show_all'
  get '/pending_turns', to: 'turns#pending_turns'
  get '/new_manual', to: 'turns#new_manual', as: 'new_manual'
  post '/new_manual', to: 'turns#create_manual'


  # Campaigns routes
  get '/campaigns/:id/load_batch', to: 'campaigns#load_batch', as: 'load_batch'
  patch 'campaigns/:id', to: 'campaigns#update', as: 'campaign'
  get '/campaigns/:id/assign_turns', to: 'campaigns#assign_turns', as: 'assign_turns'
  post '/campaigns/:id/assign_turns', to: 'campaigns#assign_turns_to_campaign', as: 'assign_turns_to_campaign'
  # Vaccines routes
  get '/applied_vaccines/new', to: 'applied_vaccines#new', as: 'new_applied_vaccines'
  post '/applied_vaccines/new', to: 'turns#pending_turns'

  
  # Profiles routes
  
  get '/profile/me', to: 'user_profiles#me', as: 'me'
  get '/profile/me/edit', to: 'user_profiles#edit', as: 'edit_profile'
  patch '/profile/me/edit', to: 'user_profiles#update', as: 'update_profile'
  get '/auth/signin/profile', to: 'user_profiles#new', as: 'new_user_profile'
  post '/auth/signin/profile', to: 'user_profiles#create', as: 'create_user_profile'
  # Accounts routes
  get '/auth/signin/account', to: 'user_accounts#new', as: 'new_user_account'
  post '/auth/signin/account', to: 'user_accounts#create', as: 'create_user_account'
  get '/accounts/set_password', to: 'user_accounts#set_password', as: 'set_password'
  patch '/accounts/set_password', to: 'user_accounts#update_password', as: 'update_password'

  # VaccinationCenters routes
 
  patch '/vaccination_centers/edit', to: 'vaccination_centers#update', as: 'update_vaccination_center'

  resources :users, :except => [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/turn.rb
class Turn < ApplicationRecord
    enum status: { pendding: 0, assigned: 1, finished: 2, canceled: 3, lost: 4 }
    belongs_to :user
    belongs_to :campaign
    belongs_to :vaccination_center
    has_one :applied_vaccine
    has_one :vaccine, :through => :applied_vaccine

    validates :user_id, presence: true
    validates :campaign_id, presence: true
    validates :vaccination_center_id, presence: true
    validates :status, inclusion: { in: Turn.statuses.keys }
    validate :validate_date?, :has_turn_in_campaign?

    scope :lost, -> { where("status = ? AND date < ?", Turn.statuses[:assigned], Date.today)}
    scope :assigned, -> { where("status = ? AND date >= ?", Turn.statuses[:assigned], Date.today) }
    scope :pendding, -> { where("status = ? OR (status = ? AND date < ?)", Turn.statuses[:pendding], Turn.statuses[:assigned], Date.today) }

    def validate_date?
        return unless date?
        begin
            if self.date.instance_of? String
                self.date = Date.strptime(date, "%Y-%m-%d") rescue nil
            end
        rescue ArgumentError
            errors.add(:date, "must be a valid date")
            return false
        end
        if date < Date.today
            errors.add(:date, I18n.t('validations.date.after', date: Date.today.strftime("%d/%m/%Y")))
            return false
        end
        return true
    end

    def has_turn_in_campaign?
      return unless campaign_id
      if Turn.where("id != ? AND user_id = ? AND campaign_id = ? AND (status = ? OR status = ?)", id, user_id, campaign_id, Turn.statuses[:pendding], Turn.statuses[:assigned]).exists?
          errors.add(:campaign_id, I18n.t('validations.turn.has_turn_in_campaign'))
          return false
      else
          return true
      end
  end

    def self.search(search, current_user)
      turns = Turn.joins(:user, :campaign).where(date: Date.today, status: Turn.statuses[:assigned], vaccination_center_id: current_user.vaccination_center_id)
      if search
        user = User.find_by(document_number: search)
        if user #Si encuentra el usuario con DNI ingresado
          temp_turns = turns.find_all { |turn| turn.user_id == user.id }
          if temp_turns.length >0 #Si encuentra un turno pedido por el usuario 
            return [temp_turns, { :success => true }]
          else #encuentra el dni, pero no tiene turno
            return [turns, { :error => I18n.t('turn.no_turno') }]
          end
        else #no hay dni en el sistema
          return [turns, { :error => I18n.t('turn.no_dni') }]
        end 
      else
        return [turns, { :success => true }]
      end
    end


      def self.search_status(search_status,turns)
        if search_status
          turns= turns.where(status: search_status)
          if turns #encuentra turnos con ese status
            return [turns, {:succes => true }]
          else #no encuentra turnos
            eturn [turns, { :error => I18n.t('turn.no_date') }]
          end
        else
          return [turns, {:success => true}]
        end
        return [turns, { :success => true }]
      end


      def self.search_date(search_date, turns)
        if search_date
          turns= turns.where(date: search_date)
          if turns #Si encuentra turnos con esa fecha
            return [turns, { :success => true }]
          else #si no encuentra turnos
            return [turns, { :error => I18n.t('turn.no_date') }]
          end
        else
          return [turns, {:success => true}]
        end
        return [turns, { :success => true }]
      end


      def self.search_vaccination_center(search_vaccination_center,turns)
        if search_vaccination_center
          turns= turns.where(vaccination_center_id: search_vaccination_center)
          if turns #encuentra turnos con ese centro de vacunacion
            return [turns, {:succes => true }]
          else #no encuentra turnos
            eturn [turns, { :error => I18n.t('turn.no_vaccination_center') }]
          end
        else
          return [turns, {:success => true}]
        end
        return [turns, { :success => true }]
      end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  include SessionsHelper, VaccinesHelper, RolesHelper, TurnsHelper
  before_action :set_turn, only: %i[ show edit update destroy ]

  # GET /turns or /turns.json
  def index
    @turns = Turn.where(user_id: current_user.id)
    @pedding_turns = @turns.where(status: Turn.statuses[:pendding])
    @assigned_turns = @turns.where(status: Turn.statuses[:assigned])
    @finished_turns = @turns.where(status: Turn.statuses[:finished])
   end

  def show_all
    @turns=Turn.all
    if params[:search_date]
      @turns, @message = @turns.search_date(params[:search_date], @turns)
      if @message[:error].present?
        flash[:error] = @message[:error]
      else
        @turns
      end
    end
    if params[:search_status]
      @turns, @message = @turns.search_status(params[:search_status],@turns)
      if @message[:error].present?
        flash[:error] = @message[:error]
      else
        @turns
      end
    end
    if params[:search_vaccination_center]
      @turns, @message = @turns.search_vaccination_center(params[:search_vaccination_center],@turns)
      if @message[:error].present?
        flash[:error] = @message[:error]
      else
        @turns
      end
    end
    
  end

  # GET /turns/1 or /turns/1.json
  def show
  end

  # GET /turns/new
  def new
    @turn = Turn.new
  end

  # GET /turns/1/edit
  def edit
  end

  # POST /turns or /turns.json
  def create
    @turn = Turn.new(turn_params)
    @turn.user_id = current_user.id

    respond_to do |format|
      if @turn.save
        flash[:success] = I18n.t('base_text.success_saved')
        format.html { redirect_to turns_url }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # GET /turns/new_manual
  def new_manual
    @turn = Turn.new
  end

  # POST /show_all
  def create_manual
    @turn = Turn.new(turn_params)
    @turn.vaccination_center_id = current_user.vaccination_center_id
    @turn.status = Turn.statuses[:assigned]
    @turn.date = Date.today
    respond_to do |format|
      if get_quantity_of_vaccines_available(Vaccine.where(campaign_id: @turn.campaign_id)) == 0
        flash[:danger] = I18n.t('base_text.error_vaccines')
        format.html { redirect_to pending_turns_url}
      else
        if @turn.save
          flash[:success] = I18n.t('base_text.success_saved_t')
          format.html { redirect_to pending_turns_url }
       else
          format.html { render :new_manual, status: :unprocessable_entity }
        end
      end
    end
  end
 

  # PATCH/PUT /turns/1 or /turns/1.json
  def update
    respond_to do |format|
      if @turn.update(turn_params)
        format.html { redirect_to @turn }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turns/1 or /turns/1.json
  def destroy
    @turn.destroy
    respond_to do |format|
      format.html { redirect_to turns_url }
    end
  end

  def pending_turns
    @campaigns = Campaign.all
    @turns, message = Turn.search(params[:search], current_user)
    if message[:error].present?
      flash[:danger] = message[:error]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turn
      @turn = Turn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turn_params
      params.require(:turn).permit(:campaign_id, :vaccination_center_id, :user_id)
    end

end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/turns/_form.html.erb
<%= form_with(model: turn, html: {class: "auth-form row needs-validation", validate: "validate"}) do |form| %>
  <% if turn.errors.any? %>
    <div id="error_explanation">
      <h2>Se encontraron <%= pluralize(turn.errors.count, "error") %> </h2>

      <ul>
        <% turn.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% invalid = turn.errors.include?(:campaign_id) %>
  <div class="form-group col-12 mb-3">
    <%= form.label :campaign, t('turn.campaign'), class: "form-label" %>
    <%= form.collection_select :campaign_id, Campaign.all, :id, :name, { prompt: true }, { class: "form-select #{'is-invalid' if invalid}" } %>
    <% if invalid %>
      <div class="invalid-feedback">
        <%= show_errors turn, :campaign %>
      </div>
    <% end %>
  </div>

  <% invalid = turn.errors.include?(:vaccination_center) %>
  <div class="form-group col-12 mb-3">
    <%= form.label :vaccination_center, t('turn.vaccination_center'), class: "form-label" %>
    <%= form.collection_select :vaccination_center_id, VaccinationCenter.all, :id, :name, { prompt: true }, { class: "form-select #{'is-invalid' if invalid}" } %>
    <% if invalid %>
      <div class="invalid-feedback">
        <%= show_errors turn, :vaccination_center %>
      </div>
    <% end %>
  </div>
  <div class="actions row">
    <div class="col-12 d-flex justify-content-lef">
      <%= link_to t('base_text.back'), turns_path, class: "btn btn-outline-primary" %>
      <%= form.submit button_text, class: "btn btn-primary mx-3", formvalidate: true %>
    </div>
  </div>
<% end %>

app/views/turns/_form_manual.html.erb
<%= form_with(model: turn,url: path, html: {class: "auth-form row needs-validation", validate: "validate"}) do |form| %>
  <% if turn.errors.any? %>
    <div id="error_explanation">
      <h2>Se encontraron <%= pluralize(turn.errors.count, "error") %> </h2>

      <ul>
        <% turn.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% invalid = turn.errors.include?(:campaign_id) %>
<div class="form-group col-12 mb-3">
  <%= form.label :campaign, t('turn.campaign'), class: "form-label" %>
  <%= form.collection_select :campaign_id, Campaign.all, :id, :name, { prompt: true }, { class: "form-select #{'is-invalid' if invalid}" } %>
  <% if invalid %>
    <div class="invalid-feedback">
      <%= show_errors turn, :campaign %>
    </div>
  <% end %>
</div>

  <div class="form-group col-12 mb-3">
    <%= form.label :last_name, t('turn.patient'), class: "form-label" %>
    <%= form.collection_select :user_id, User.all, :id, :name_with_initial, { prompt: true }, { class: "form-select #{'is-invalid' if invalid}" } %>
    <% if invalid %>
      <div class="invalid-feedback">
        <%= show_errors turn, :campaign %>
      </div>
    <% end %>
  </div>

  
  <div class="actions row">
    <div class="col-12 d-flex justify-content-lef">

      <%= form.submit "Confirmar", class: "btn btn-primary mx-3", formvalidate: true %>
    </div>
  </div>
<% end %>

app/views/turns/edit.html.erb
<h1>Editing Turn</h1>

<%= render 'form', turn: @turn, button_text: t('turn.request_button') %>

<%= link_to 'Show', @turn %> |

app/views/turns/index.html.erb
<div class="row mb-4">
  <div class="col-12 d-flex justify-content-between align-items-center">
    <h1>
      <%= t 'sidebar.my_shifts' %>
    </h1>
    <%= link_to t('turn.request_a_turn'), new_turn_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="row">
  <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 mb-3">
    <div class="card">
      <div class="card-header">
        <h2>
          <%= t 'turn.assigned' %>
        </h2>
      </div>
      <div class="card-body <%= 'empty' unless @assigned_turns.length > 0 %>">
        <% if @assigned_turns.length > 0 %>
        <table class="table">
          <thead>
            <tr>
              <th>
                <%= t 'turn.campaign' %>
              </th>
              <th>
                <%= t 'turn.date' %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @assigned_turns.each do |turn| %>
              <tr>
                <td><%= turn.campaign.name %></td>
                <td><%= turn.date %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% else %>
          <p>
            <%= t 'turn.no_assigned' %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 mb-3">
    <div class="card">
      <div class="card-header">
        <h2>
          <%= t 'turn.finished' %>
        </h2>
      </div>
      <div class="card-body <%= 'empty' unless @finished_turns.length > 0 %>">
        <% if @finished_turns.length > 0 %>
        <table class="table">
          <thead>
            <tr>
              <th>
                <%= t 'turn.campaign' %>
              </th>
              <th>
                <%= t 'turn.date' %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @assigned_turns.each do |turn| %>
              <tr>
                <td><%= turn.campaign.name %></td>
                <td><%= turn.date %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% else %>
          <p>
            <%= t 'turn.no_finished' %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 mb-3">
  <div class="card">
      <div class="card-header">
        <h2>
          <%= t 'turn.pendding' %>
        </h2>
      </div>
      <div class="card-body <%= 'empty' unless @pedding_turns.length > 0 %>">
       <% if @pedding_turns.length > 0 %>
       <table class="table">
          <thead>
            <tr>
              <th>
                <%= t 'turn.campaign' %>
              </th>
              <th>
                <%= t 'turn.date' %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @assigned_turns.each do |turn| %>
              <tr>
                <td><%= turn.campaign.name %></td>
                <td><%= turn.date %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% else %>
          <p>
              <%= t 'turn.no_pedding' %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/turns/new.html.erb
<h1>
    <%= t 'turn.request_a_turn' %>
</h1>

<%= render 'form', turn: @turn, button_text: t('turn.request_button') %>

app/views/turns/new_manual.html.erb
<h1>
    <%= t 'turn.manual_assign' %>
</h1>

<%= render 'form_manual', turn: @turn,path: new_manual_url, button_text: t('turn.request_button') %>

app/views/turns/pending_turns.html.erb
<div class="row mb-4">
  <div class="col-12 d-flex justify-content-between align-items-center">
    <h1>
    Turnos del dia  <%= Date.today %>
    </h1>
  </div>
</div>
<%= form_tag pending_turns_path, method: :get, class: "row mb-4 needs-validation d-flex flex-row justify-content-start align-items-center", validate: "validate" do %>
  <%= number_field_tag :search, params[:search], placeholder: "Ingresá un número de DNI para buscar un paciente", class: "form-control ms-3 col-10", required: true, min: 10000, style: "width: auto" %>
  <%= submit_tag("Buscar",:name => nil, class: "ms-2 col-2 btn btn-primary")%>
<% end %>

<div class="row">
  <div class="col-12 mb-4">
    <%= link_to t('turn.add_user'), new_user_path ,class: "btn btn-outline-secondary" %>
    <%= link_to t('turn.manual_assign'), new_manual_path, class: "btn btn-outline-primary" %>
  </div>
</div>

<div class="row">
  <% @campaigns.each do |campaign| %>
    <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 mb-3">
      <div class="card">
        <div class="card-header">
          <h2>
            <%= campaign.name %>
          </h2>
        </div>
        <% turns = @turns.find_all { |turn| turn.campaign_id == campaign.id } %>
        <div class="card-body <%= 'empty' unless turns.length > 0 %>">
          <% if turns.length > 0 %>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">
                    <%= t 'document' %>
                  </th>
                  <th scope="col">
                    <%= t 'turn.patient' %>
                  </th>
                  <th scope="col">
                    <%= t 'base_text.actions' %>
                  </th>
                </tr>
              </thead>
              <tbody>
                <% turns.each do |turn| %>
                  <tr>
                    <td scope="row">
                      <%= turn.user.document_number %>
                    </td>
                    <td>
                      <%= turn.user.first_name %> <%= turn.user.last_name %>
                    </td>
                    <td>
                      <%= link_to t('vaccines.load_vaccine'), { controller: "applied_vaccines", action: "new", turn: turn }, class: "btn btn-outline-primary btn-sm" %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p>
              <%= t 'turn.empty' %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/turns/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_turn_path(@turn) %> |
<%= link_to 'Back', turns_path %>

app/views/turns/show_all.html.erb
<div class="row mb-4">
  <div class="col-12 d-flex align-items-center">
    <%= link_to t('turn.today'), pending_turns_path, class: "btn btn-primary" %>
    <% if has_role?(:vacunador,current_user) %>
      <%= link_to t('turn.manual_assign'), new_manual_path, class: "btn btn-secondary mx-3" %>
    <% end %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-4">
    <%= form_tag @turnos, :method => "get" do %>
      <h4>
        <%= label_tag(:search_date, "Filtrar por fecha") %>
      </h4>
      <%= date_field_tag :search_date, params[:search], class: 'form-control mb-3' %>
      <%= submit_tag("Filtrar",:date => nil, class: "btn btn-outline-primary")%>
    <% end %>
  </div>

  <div class="col-4">
    <%= form_tag @turnos, :method => "get" do %>
      <h4>
        <%= label_tag(:search_status, "Filtrar por estado") %>
      </h4>
      <%= select_tag :search_status, options_for_select(Turn.statuses.map { |key,value| [t(key), value] }), class: 'form-select mb-3' %>
      <%= submit_tag("Filtrar", class: "btn btn-outline-primary")%>
    <% end %>
  </div>

  <div class="col-4">
    <%= form_tag @turnos, :method => "get" do %>
      <h4>
        <%= label_tag(:search_status, "Filtrar por centro de vacunacion") %>
      </h4>
      <%= select_tag :search_vaccination_center, options_for_select(VaccinationCenter.all.map { |vaccination_center| [vaccination_center.name, vaccination_center.id] }), class: 'form-select mb-3' %>
      <%= submit_tag("Filtrar", class: "btn btn-outline-primary")%>
    <% end %>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12 mb-3">
    <div class="card">
      <div class="card-header">
        <h2>
          <%= t 'sidebar.turns' %>
        </h2>
      </div>
      <div class="card-body <%= 'empty' unless @turns.length > 0 %>">
        <% if @turns.length > 0 %>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">
                <%= t 'document' %>
              </th>
              <th scope="col">
                <%= t 'turn.patient' %>
              </th>
              <th scope="col">
                <%= t 'turn.campaign' %>
              </th>
              <th scope="col">
                <%= t 'turn.status' %>
              </th>
              <th scope="col">
                <%= t 'turn.date' %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @turns.each do |turn| %>
              <tr>
                <td><%= turn.user.document_number %></td>
                <td><%= turn.user.first_name + turn.user.last_name %></td>
                <td><%= turn.campaign.name %></td>
                <td><%= t turn.status %> </td>
                <td><%= t turn.date.strftime("%d/%m/%Y") %> </td>
              </tr>
            <% end %>
          </tbody>
          
        </table>
        <% else %>
          <p>
            <%= t 'turn.no_turns' %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>