config/routes.rb
Rails.application.routes.draw do
  resources :vaccination_centers
  resources :vaccines
  resources :turns
  resources :applied_vaccines, :path => 'applied_vaccine'
  root 'user_profiles#me'

  # Sessions routes
  get '/auth/login', to: 'sessions#login'
  post '/auth/login', to: 'sessions#create'
  get '/auth/logout', to: 'sessions#destroy'

  # Turns routes
  get '/show_all', to: 'turns#show_all', as: 'show_all'
  get '/pending_turns', to: 'turns#pending_turns'
  get '/new_manual', to: 'turns#new_manual', as: 'new_manual'
  post '/new_manual', to: 'turns#create_manual'


  # Campaigns routes
  get '/campaigns/:id/load_batch', to: 'campaigns#load_batch', as: 'load_batch'
  patch 'campaigns/:id', to: 'campaigns#update', as: 'campaign'
  get '/campaigns/:id/assign_turns', to: 'campaigns#assign_turns', as: 'assign_turns'
  post '/campaigns/:id/assign_turns', to: 'campaigns#assign_turns_to_campaign', as: 'assign_turns_to_campaign'
  # Vaccines routes
  get '/applied_vaccines/new', to: 'applied_vaccines#new', as: 'new_applied_vaccines'
  post '/applied_vaccines/new', to: 'turns#pending_turns'

  
  # Profiles routes
  
  get '/profile/me', to: 'user_profiles#me', as: 'me'
  get '/profile/me/edit', to: 'user_profiles#edit', as: 'edit_profile'
  patch '/profile/me/edit', to: 'user_profiles#update', as: 'update_profile'
  get '/auth/signin/profile', to: 'user_profiles#new', as: 'new_user_profile'
  post '/auth/signin/profile', to: 'user_profiles#create', as: 'create_user_profile'
  # Accounts routes
  get '/auth/signin/account', to: 'user_accounts#new', as: 'new_user_account'
  post '/auth/signin/account', to: 'user_accounts#create', as: 'create_user_account'
  get '/accounts/set_password', to: 'user_accounts#set_password', as: 'set_password'
  patch '/accounts/set_password', to: 'user_accounts#update_password', as: 'update_password'

  # VaccinationCenters routes
 
  patch '/vaccination_centers/edit', to: 'vaccination_centers#update', as: 'update_vaccination_center'

  resources :users, :except => [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vaccine.rb
class Vaccine < ApplicationRecord
    belongs_to :campaign
    has_many :applied_vaccines

    validates :name, presence: true, length: { maximum: 50, minimum: 3 }
    validates :number_of_doses, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
    validates :stock, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates :campaign_id, presence: true, allow_blank: false
end

app/controllers/vaccines_controller.rb
class VaccinesController < ApplicationController
  include SessionsHelper, VaccinesHelper
  before_action :set_vaccine, only: %i[ show edit update destroy ]

  # GET /vaccines or /vaccines.json
  def index
    @campaigns = Campaign.where("end_date <= ?", Date.today).order(:start_date)
  end

  # GET /vaccines/1 or /vaccines/1.json
  def show
  end

  # GET /vaccines/new
  def new
    @vaccine = Vaccine.new(campaign_id: params[:campaign])
  end

  # GET /vaccines/1/edit
  def edit
  end

  # POST /vaccines or /vaccines.json
  def create
    @vaccine = Vaccine.new(vaccine_params)

    respond_to do |format|
      if @vaccine.save
        format.html { redirect_to @vaccine, notice: "Vaccine was successfully created." }
        format.json { render :show, status: :created, location: @vaccine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vaccines/1 or /vaccines/1.json
  def update
    respond_to do |format|
      if @vaccine.update(vaccine_params)
        format.html { redirect_to @vaccine, notice: "Vaccine was successfully updated." }
        format.json { render :show, status: :ok, location: @vaccine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccines/1 or /vaccines/1.json
  def destroy
    @vaccine.destroy
    respond_to do |format|
      format.html { redirect_to vaccines_url, notice: "Vaccine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vaccine
      @vaccine = Vaccine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vaccine_params
      params.require(:vaccine).permit(:name, :campaign_id, :stock, :number_of_doses)
    end
end

app/helpers/vaccines_helper.rb
module VaccinesHelper

    def get_quantity_of_vaccines_available(campaign)
        
        if has_role? :vacunador
            lost_turns = Turn.lost.where(campaign_id: campaign.id, vaccination_center_id: current_user.vaccination_center_id).count
            return lost_turns
        else
            assigned_turns = Turn.assigned.where(campaign_id: campaign.id).count
            return campaign.stock - assigned_turns
        end
    end

end

app/views/vaccines/_form.html.erb
<%= form_for vaccine do |form| %>
  <% if vaccine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vaccine.errors.count, "error") %> prohibited this vaccine from being saved:</h2>

      <ul>
        <% vaccine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% invalid = vaccine.errors.include?(:campaign_id) %>
  <div class="form-group col-12 mb-3">
    <%= form.label :campaign_id, t('turn.campaign'), class: "form-label" %>
    <%= form.collection_select :campaign_id, Campaign.all, :id, :name, { prompt: true }, { class: "form-select #{'is-invalid' if invalid}", disabled: !!vaccine.campaign_id } %>
    <% if invalid %>
      <div class="invalid-feedback">
        <%= show_errors vaccine, :campaign %>
      </div>
    <% end %>
  </div>

  <% invalid = vaccine.errors.include?(:name) %>
  <div class="form-group col-12 mb-3">
      <%= form.label :name, t("base_text.name"), class: "form-label" %>
      <%= form.text_field :name, placeholder: t("vaccines.name_placeholder"), class: "form-control #{'is-invalid' if invalid}" %>
      <% if invalid %>
          <div class="invalid-feedback">
              <%= show_errors vaccine, :name %>
          </div>  
      <% end %>
  </div>

  <% invalid = vaccine.errors.include?(:number_of_doses) %>
  <div class="form-group col-12 mb-3">
      <%= form.label :number_of_doses, t("vaccines.number_of_doses"), class: "form-label" %>
      <%= form.number_field :number_of_doses, placeholder: t("vaccines.number_of_doses_placeholder"), class: "form-control #{'is-invalid' if invalid}", min: 1 %>
      <% if invalid %>
          <div class="invalid-feedback">
              <%= show_errors vaccine, :number_of_doses %>
          </div>  
      <% end %>
  </div>

  <% invalid = vaccine.errors.include?(:stock) %>
  <div class="form-group col-12 mb-3">
      <%= form.label :stock, t("vaccines.stock"), class: "form-label" %>
      <%= form.number_field :stock, disabled: !!vaccine.id, placeholder: t("vaccines.stock_placeholder"), class: "form-control #{'is-invalid' if invalid}", min: 0 %>
      <% if invalid %>
          <div class="invalid-feedback">
              <%= show_errors vaccine, :stock %>
          </div>  
      <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<!--
<select class="form-select " disabled="disabled" name="vaccine[campaign_id]" id="vaccine_campaign_id">
  <option selected="selected" value="1">SARS-COV2</option>
  <option value="2">Fiebre amarilla</option>
  <option value="3">Gripe común</option>
</select>
<select class="form-select " disabled="disabled" name="vaccine[campaign_id]" id="vaccine_campaign_id">
  <option selected="selected" value="1">SARS-COV2</option>
  <option value="2">Fiebre amarilla</option>
  <option value="3">Gripe común</option>
</select>
-->

app/views/vaccines/edit.html.erb
<h1>Editing Vaccine</h1>

<%= render 'form', vaccine: @vaccine %>

<%= link_to 'Show', @vaccine %> |
<%= link_to 'Back', vaccines_path %>

app/views/vaccines/index.html.erb
<div class="row mb-4">
  <div class="col-12 d-flex justify-content-between align-items-center">
    <h1>
      <%= t 'vaccines.title' %>
    </h1>
  </div>
</div>


<div class="row">
  <% @campaigns.each do |campaign| %>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-3">
      <div class="card">
        <div class="card-header">
          <h2>
            <%= campaign.name %>
          </h2>
        </div>
        <div class="card-body text-center">
          <% if campaign.stock > 0 %>
            <div class="alert alert-primary">
              <%= get_quantity_of_vaccines_available campaign %> <%= t 'vaccines.vaccines_available' %>
            </div>
          <% else %>
            <div class="alert alert-danger">
              <%= t 'vaccines.no_vaccines_available' %>
            </div>
          <% end %>
          <% if has_role?([:directivo, :administrador]) %>
            <%= link_to t('vaccines.load_batch'), load_batch_url(campaign), class: "btn btn-outline-primary btn-sm" %>
          <%= link_to t('vaccines.assign_shifts'), assign_turns_url(campaign), class: "btn btn-outline-secondary btn-sm" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/vaccines/new.html.erb
<h1>New Vaccine</h1>

<%= render 'form', vaccine: @vaccine %>

<%= link_to 'Back', vaccines_path %>

app/views/vaccines/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vaccine_path(@vaccine) %> |
<%= link_to 'Back', vaccines_path %>