config/routes.rb
Rails.application.routes.draw do
  resources :vaccination_centers
  resources :vaccines
  resources :turns
  resources :applied_vaccines, :path => 'applied_vaccine'
  root 'user_profiles#me'

  # Sessions routes
  get '/auth/login', to: 'sessions#login'
  post '/auth/login', to: 'sessions#create'
  get '/auth/logout', to: 'sessions#destroy'

  # Turns routes
  get '/show_all', to: 'turns#show_all', as: 'show_all'
  get '/pending_turns', to: 'turns#pending_turns'
  get '/new_manual', to: 'turns#new_manual', as: 'new_manual'
  post '/new_manual', to: 'turns#create_manual'


  # Campaigns routes
  get '/campaigns/:id/load_batch', to: 'campaigns#load_batch', as: 'load_batch'
  patch 'campaigns/:id', to: 'campaigns#update', as: 'campaign'
  get '/campaigns/:id/assign_turns', to: 'campaigns#assign_turns', as: 'assign_turns'
  post '/campaigns/:id/assign_turns', to: 'campaigns#assign_turns_to_campaign', as: 'assign_turns_to_campaign'
  # Vaccines routes
  get '/applied_vaccines/new', to: 'applied_vaccines#new', as: 'new_applied_vaccines'
  post '/applied_vaccines/new', to: 'turns#pending_turns'

  
  # Profiles routes
  
  get '/profile/me', to: 'user_profiles#me', as: 'me'
  get '/profile/me/edit', to: 'user_profiles#edit', as: 'edit_profile'
  patch '/profile/me/edit', to: 'user_profiles#update', as: 'update_profile'
  get '/auth/signin/profile', to: 'user_profiles#new', as: 'new_user_profile'
  post '/auth/signin/profile', to: 'user_profiles#create', as: 'create_user_profile'
  # Accounts routes
  get '/auth/signin/account', to: 'user_accounts#new', as: 'new_user_account'
  post '/auth/signin/account', to: 'user_accounts#create', as: 'create_user_account'
  get '/accounts/set_password', to: 'user_accounts#set_password', as: 'set_password'
  patch '/accounts/set_password', to: 'user_accounts#update_password', as: 'update_password'

  # VaccinationCenters routes
 
  patch '/vaccination_centers/edit', to: 'vaccination_centers#update', as: 'update_vaccination_center'

  resources :users, :except => [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_profile.rb
class UserProfile
    include ActiveModel::Model
    include ActiveModel::Validations
    include UsersHelper

    attr_accessor :first_name, :last_name, :document_number, :birthdate, :comorbidity
    validates :first_name, :presence => true, length: { minimum: 2 }
    validates :last_name, :presence => true, length: { minimum: 2 }
    validates :document_number, :presence => true, numericality: { only_integer: true, greater_than_or_equal_to: 10000 }
    validates :birthdate, :presence => true
    validate :validate_birthdate?, :document_number_uniqueness?
    validates_presence_of :comorbidity, :in => [true, false]

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
    include SessionsHelper, RolesHelper
    skip_before_action :require_login, only: [:new, :create]
    layout 'auth'

    def me
        @user = current_user
        render layout: 'application'
    end

    def edit
        @user_profile = current_user
        render layout: 'application'
    end

    def update
        @user_profile = current_user
        user_params = params.require(:user).permit(
            :first_name,
            :last_name,
            :document_number,
            :birthdate,
            :comorbidity
        )
        if @user_profile.update(user_params)
            flash[:success] = I18n.t('base_text.success')
            redirect_to me_path
        else
            flash[:danger] = I18n.t('base_text.error')
            render layout: 'application', :action => :edit
        end
    end

    def new
        # An instance of UserProfile is created just the
        # same as you would for any Active Record object.
        @user_profile = UserProfile.new

        if logged_in?
            if is_organization_member?
                render layout: 'application'
            else
                redirect_to root_path
            end
        end
    end
  
    def create
        # Again, an instance of UserProfile is created
        # just the same as you would for any Active
        # Record object.
        @user_profile = UserProfile.new(user_profile_params)
  
        # The valid? method is also called just the same
        # as for any Active Record object.
        if @user_profile.valid?
  
            # Instead of persisting the values to the
            # database, we're temporarily storing the
            # values in the session.
            session[:user_profile] = {
                'first_name' => @user_profile.first_name,
                'last_name' => @user_profile.last_name,
                'document_number' => @user_profile.document_number,
                'birthdate' => @user_profile.birthdate,
                'comorbidity' => @user_profile.comorbidity
            }

            redirect_to new_user_account_path
        else
            if logged_in?
                if is_organization_member?
                    render layout: 'application', template: 'user_profiles/new'
                else
                    redirect_to root_path
                end
            else
                render :new
            end
        end
    end
  
      private
  
      # The strong params work exactly as they would
      # for an Active Record object.
    def user_profile_params
        params.require(:user_profile).permit(
            :first_name,
            :last_name,
            :document_number,
            :birthdate,
            :comorbidity
        )
    end
end

app/views/user_profiles/_form.html.erb
<% adjective = logged_in? ? t('adjective.third') :  t('adjective.second') %>
<%= form_for @user_profile, url: path, html: {class: "auth-form row needs-validation", validate: "validate"} do |f| %>
    <h1>
        <%= title %>
    </h1>

    <% invalid = @user_profile.errors.include?(:first_name) %>
    <div class="form-group col-12 mb-3">
        <%= f.label :first_name, t(:first_name), class: "form-label" %>
        <%= f.text_field :first_name, placeholder: t(:first_name_placeholder, adjective: adjective), class: "form-control #{'is-invalid' if invalid}" %>
        <% if invalid %>
            <div class="invalid-feedback">
                <%= show_errors @user_profile, :first_name %>
            </div>  
        <% end %>
    </div>

    <% invalid = @user_profile.errors.include?(:last_name) %>
    <div class="form-group col-12 mb-3">
        <%= f.label :last_name, t(:last_name), class: "form-label" %>
        <%= f.text_field :last_name, placeholder: t(:last_name_placeholder, adjective: adjective), class: "form-control #{'is-invalid' if invalid}" %>
        <% if invalid %>
            <div class="invalid-feedback">
                <%= show_errors @user_profile, :last_name %>
            </div>
        <% end %>
    </div>

    <% invalid = @user_profile.errors.include?(:document_number) %>
    <div class="form-group col-12 mb-3">
        <%= f.label :document_number, t(:document_number), class: "form-label" %>
        <%= f.number_field :document_number, placeholder: t(:document_number_placeholder, adjective: adjective), class: "form-control #{'is-invalid' if invalid}" %>
        <% if invalid %>
            <div class="invalid-feedback">
                <%= show_errors @user_profile, :document_number %>
            </div>
        <% end %>
    </div>

    <% invalid = @user_profile.errors.include?(:birthdate) %>
    <div class="form-group col-12 mb-3">
        <%= f.label :birthdate, t(:birthdate), class: "form-label" %>
        <% if @user_profile.birthdate.to_s.strip.length > 0 %>
            <%= f.date_field :birthdate, as: :date, value: f.object.try(:to_time).try(:strftime,"%Y %m %d"), :max => (Date.today - 6.years), min: "1900-01-01", placeholder: 'dd/MM/AAAA', class: "form-control #{'is-invalid' if invalid}" %>
        <% else %>
            <%= f.date_field :birthdate, as: :date, :value => (Date.today - 6.years), :max => (Date.today - 6.years), min: "1900-01-01", placeholder: 'dd/MM/AAAA', class: "form-control #{'is-invalid' if invalid}" %>
        <% end %>
        
        <% if invalid %>
            <div class="invalid-feedback">
                <%= show_errors @user_profile, :birthdate %>
            </div>
        <% end %>
    </div>

    <div class="form-group col-12 mb-3">
        <%= f.label :comorbidity, t(:comorbidity_question), class: "form-label" %>
        <div class="d-flex justify-content-around">
            <div class="form-check form-check-inline">
                <%= f.label :comorbidity, t('base_text.yes'), :value => "true", class: "form-check-label" %>
                <%= f.radio_button :comorbidity, true, checked: @user_profile.comorbidity, class: "form-check-input" %>
            </div>
            <div class="form-check form-check-inline">
                <%= f.label :comorbidity, t('base_text.no'), :value => "false", class: "form-check-label" %>
                <%= f.radio_button :comorbidity, false, checked: !@user_profile.comorbidity, class: "form-check-input" %>
            </div>
        </div>
    </div>
    <%= f.submit button_text, class: "btn btn-primary", formvalidate: true %>
<% end %>

app/views/user_profiles/edit.html.erb
<div class="row">
 <div class="col d-flex justify-content-center">
    <%= render partial: "form", locals: {title: t('profile.edit_title'), button_text: t('base_text.save'), path: update_profile_path } %>
 </div>
</div>

app/views/user_profiles/me.html.erb
<%= content_for :page_title do %>
    <%= t 'sidebar.my_profile' %>
<% end %>
<h1>Bienvenido</h1>
<div class="card">
    <div clas="card-header">
        <h2>
            <%= t 'profile.title' %>
        </h2>
    </div>

    <% age = ((Time.zone.now - @user.birthdate.to_time) / 1.year.seconds).floor %>

    <div class="card-body">
        <h5 class="card-title">
            <%= @user.first_name %> (<%= age %> <%= t 'base_text.years' %>)
        </h5>
        <p class="card-text">
            <%= @user.email %>
        </p>
        <p class="card-text">
            <%= t 'base_text.dni' %> <%= @user.document_number %> <%=  %>
        </p>
        <% if @user.comorbidity %>
            <p class="card-text"> 
                <%= t 'profile.comorbidity' %>
            </p>
        <% else %>
            <p class="card-text"> 
                <%= t 'profile.no_comorbidity' %>
            </p>
        <% end %>
        <%= link_to t('profile.edit_button'), edit_profile_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/user_profiles/new.html.erb
<% if !logged_in? %>
    <%= stylesheet_link_tag 'sessions', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% title = t('auth.sign_in.first_step.title') %>
<% else %>
    <% title = t('add_user.first_step.title') %>
<% end %>

<%= render partial: "form", locals: {title: title, button_text: t('base_text.continue'), path: create_user_profile_path }%>
<% if !logged_in? %>
    <div class="mb-3 mt-3 text-center invite-container">
        <p class="invite">
            <%= t 'auth.sign_in.account' %>
            <%= link_to t('auth.sign_in.login_invite'), auth_login_path%>
        </p>
    </div>
<% end %>